---
epel_package: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
epel_key_url: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"

registry_config_dir: /etc/registry
registry_config_src: templates/config.yml.j2
registry_container: "registry:2.8"
registry_svc_name: "docker.registry.service"
registry_docker_volume_name: "registry"
registry_port: "5000"
registry_state: started
registry_enabled: yes

################
registry_cfg_scrape_interval: 15s
registry_cfg_evaluation_interval: 15s

# To configure the container registry as a pull-through cache, set
# standalone_container_registry_cache_enable to true.
# A username and password can optionally be configured to access private images
# or take advantage of higher rate limits in a pro account.
standalone_container_registry_cache_enable: false
standalone_container_registry_cache_upstream: "https://registry-1.docker.io"
# standalone_container_registry_cache_username:
# standalone_container_registry_cache_password:
