---
- name: create config dir
  file:
    path: "{{ registry_config_dir }}"
    state: directory
    mode: "0755"

- name: install config file
  template:
    src: "{{ registry_config_src }}"
    dest: "{{ registry_config_dir }}/config.yml"
    owner: root
    group: root
    mode: 0644
  notify: restart registry

- name: trust GPG key for EPEL
  rpm_key:
    key: "{{ epel_key_url }}"
    state: present
  when: ansible_os_family == "RedHat"

- name: Enable EPEL repo
  package:
    name:
      - "{{ epel_package }}"
    state: present
  when: ansible_os_family == 'RedHat'

- name: Ensure Python 2 dependencies are installed via OS packages
  when: (ansible_python.version.major==2) and (ansible_python.version.minor==7)
  block:
  - name: install python-docker
    package:
      name: python-docker

- name: Ensure Python 3 dependencies are installed via pip
  when: ansible_python.version.major==3
  block:
  - name: install pip
    package:
      name: python3-pip
  - name: install docker
    pip:
      name: docker

- name: create a persistent docker volume for metrics
  docker_volume:
    name: "{{ registry_docker_volume_name }}"
    state: "present"

- name: install systemd unit file
  template:
    src: templates/docker.registry.service.j2
    dest: "/etc/systemd/system/{{ registry_svc_name }}"
    owner: root
    group: root
    mode: 0644
  notify: restart registry

- name: configure service
  systemd:
    name: "{{ registry_svc_name }}"
    state: "{{ registry_state }}"
    enabled: "{{ registry_enabled }}"
    daemon_reload: yes
  notify: restart registry